
CXX=/homes/sharp/3rdparty/mpich2/mpich2-1.1.1p1/gcc/bin/mpicxx

.cpp.o:
	$(CXX) $(CFLAGS) -c $<

include /homes/iulian/lib/MOAB/lib/moab.make
include /homes/iulian/lib/MOAB/lib/iMesh-Defs.inc

# debug options
# these are for using in concert with gcov
#OPTFLAGS = -O0 -g  -fprofile-arcs -ftest-coverage
OPTFLAGS = -O0 -g  
FEATURES =

CFLAGS = $(IMESH_INCLUDES) $(MOAB_INCLUDES) $(OPTFLAGS) 
LFLAGS = $(LIBDIR) $(OPTFLAGS) 

CORE_SRCS = Qslim_test.cpp QslimOptions.cpp QslimDecimation.cpp \
              3D.cpp  quadrics.cpp \
	     Heap.cpp Mat4.cpp primitives.cpp

QSLIM_SRCS = $(CORE_SRCS)
QSLIM_OBJS = $(QSLIM_SRCS:.cpp=.o)



qslim2     : $(QSLIM_OBJS)
	$(CXX) -o $@ $(QSLIM_OBJS) $(OPTFLAGS) -lm $(IMESH_LIBS)\
		 $(MOAB_LIBS_LINK)


clean:
	rm -rf *.o qslim2
