#hdf5 supports CMake
add_external_project(hdf5
  DEPENDS zlib szip
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=TRUE
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=TRUE
    -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=TRUE
    -DHDF5_ENABLE_SZIP_ENCODING:BOOL=TRUE
    -DHDF5_BUILD_HL_LIB:BOOL=TRUE
    -DSZIP_LIBRARY:FILEPATH=<INSTALL_DIR>/lib/libsz${CMAKE_SHARED_LIBRARY_SUFFIX}
    -DSZIP_INCLUDE_DIR:FILEPATH=<INSTALL_DIR>/include
)
