## script to create a cylinder around the entire core, set pitch, rings, radius, and height values.
#{pitch = 10}
#{rings = 3}
#{rd = 40}
#{ht = 100}
create cylinder height {ht} radius {rd}
section vol 1 with xplane reverse
section vol 1 with yplane 
webcut vol 1 with plane xplane offset 0 rotate 30 about z
delete vol 2
#{x0 = - (rings-1)*pitch*sind(30)}
#{y0 = (rings-1)*pitch*cosd(30)}
#
#{x1 = x0 - (pitch*sind(30)) /2.0 }
#{y1 = y0 + (pitch*cosd(30)) /2.0 }
#
#{x2 = x0}
#{y2 = y0 + pitch*tand(30)}
#
#{x3 = x0 + pitch/2.0}
#{y3 = y0 + (pitch*tand(30))/2.0}
#
#{x4 = 0}
#{y4 = pitch* (rings+1)*tand(30) }
#
create vertex {x1} {y1}
create vertex {x2} {y2}
create vertex {x3} {y3}
create vertex {x4} {y4}
create vertex  0 0 
#
create curve vertex 17 18
create curve vertex 18 19
create curve vertex 19 20
create curve vertex 20 21
create curve vertex 21 17
#
create surface curve 28 to 32
sweep surface 21 vector 0 0 1 distance {ht}
move vol 3 z {-ht/2.0}
subtract vol 3 from vol 1
body 1 copy reflect 1 0 0
unite vol 1 4
vol 1 copy move  x 0
vol 1 copy move  x 0
vol 1 copy move  x 0
vol 1 copy move  x 0
vol 1 copy move  x 0
rotate vol 5 angle 60 about z
rotate vol 6 angle 120 about z
rotate vol 7 angle -60 about z
rotate vol 8 angle -120 about z
rotate vol 9 angle 180 about z
save as 'outer_cylinder.cub'
